### ISSUE TITLE
[Enhancement] Works with SwitchBot Hub Plus ?

### ISSUE THREAD

**Issue by DJay-X** [yujinakayama/homebridge-switchbot#1]
@yujinakayama  Hi and thanks for your work and sharing.
Does this plugin works online direct via Bluetooth or with the SwitchBot Hub Plus?
I'm asking because I would prefer the Hub/Wifi connection.
Thanks again for the time you are investing.

**Comment by yujinakayama** [comment]
> Does this plugin works online direct via Bluetooth or with the SwitchBot Hub Plus?

It works only via Bluetooth. Currently there's no plan to support SwitchBot Hub since I do not have it.

**Comment by aschmidt74** [comment]
I'd appreciate the support of the Hub as well, as I use my RPi's 2nd serial port for other purposes, and thus can't use the internal BlueTooth.
